[package]
name = "threadnations-simulation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
threadnations-analysis = { path = "../analysis" }
threadnations-common = { path = "../common" }
threadnations-worldgen = { path = "../worldgen" }
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
