[package]
name = "threadnations-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
threadnations-analysis = { path = "../analysis" }
threadnations-common = { path = "../common" }
threadnations-simulation = { path = "../simulation" }

[lints]
workspace = true
